steps:
## Run terraform init step
- id: "terraform => init"
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        env="dev"
        cd infrastructure/environments/ishim-dev/
        terraform init \
        -backend-config=bucket="ishim-adm-tf-state" \
        -backend-config=prefix="${env}"
        cd ../../../

## Run the plan command
- id: "terraform => plan"
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        cd infrastructure/environments/ishim-dev/
        terraform plan || exit 1
        cd ../../../

## Run actual deployment step
- id: "terraform => apply"
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        if [[ ! -f "${_PR_NUMBER}" ]]; then
          cd infrastructure/environments/ishim-dev/
          terraform apply -auto-approve || exit 1
          cd ../../../
        fi

  env:
    # - 'TF_VAR_component=${_COMPONENT}'
    - 'TF_VAR_adm_project_id=$PROJECT_ID'
    # - 'TF_VAR_repo_branch=$BRANCH_NAME'
    # - 'TF_VAR_repo_commit=$REVISION_ID'
    # - 'TF_LOG=DEBUG'

substitutions:

tags: ['admin']
