steps:
## Run terraform init step
- id: "terraform => init"
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
        sfx=`if echo "${BRANCH_NAME}" | grep -Eq "^develop*"; then echo "uat"; else echo "dev"; fi`;
        env=`if echo "${BRANCH_NAME}" | grep -Eq "^release*"; then echo "prd"; else echo "${sfx}"; fi`;
        cd infrastructure/projects/ishim-dev/
        terraform init \
        -backend-config=bucket="${PROJECT_ID}-tf-state" \
        -backend-config=prefix="${env}"
        cd ../../../

## Run the plan command
- id: "terraform => plan"
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      cd infrastructure/projects/ishim-dev/
      terraform plan || exit 1
      cd ../../../

## Run actual deployment step
- id: "terraform => apply"
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      if [[ ! -f "${_PR_NUMBER}" ]]; then
        cd infrastructure/projects/ishim-dev/
        terraform apply -auto-approve
        cd ../../../
      fi

  env:
    # - 'TF_VAR_component=${_COMPONENT}'
    # - 'TF_VAR_admin_project_id=$PROJECT_ID'
    # - 'TF_VAR_repo_branch=$BRANCH_NAME'
    # - 'TF_VAR_repo_commit=$REVISION_ID'
    # - 'TF_VAR_gcp_pci_prj_prefix=${_PROJECT_ID_PREFIX}'
    # - 'TF_LOG=DEBUG'

substitutions:

tags: ['admin']
